"""Phase 2 — Financial-metrics evaluation on saved DLinear checkpoints.

Computes the Sharpe Ratio and Maximum Drawdown of a simple long-short
strategy driven by each model's predictions. No retraining required —
this is pure post-processing on the saved checkpoints.

Strategy (long-short, H-day holding period):
    For each test sample at time t (per stock):
        last_close   = X[t, -1, CLOSE_IDX]                    (price at t)
        pred_close_H = model.predict(X[t])[-1]                (predicted price at t+H)
        actual_close_H = y[t, -1]                             (true price at t+H)

        pred_return    = (pred_close_H - last_close) / last_close
        actual_return  = (actual_close_H - last_close) / last_close

        position       = sign(pred_return)        # +1 long, -1 short, 0 if exactly zero
        strategy_return = position * actual_return

Annualised Sharpe (per stock):
    sharpe = mean(strategy_return) / std(strategy_return)  *  sqrt(252 / H)

Maximum Drawdown (per stock, on the equity curve generated by compounding
strategy returns):
    eq[t] = prod_{s<=t} (1 + strategy_return[s])
    peak[t] = max_{s<=t} eq[s]
    mdd = max_t (peak[t] - eq[t]) / peak[t]

The 252/H annualisation factor assumes non-overlapping trades. With our
stride=1 sampling the trades overlap, so this is a *theoretical* Sharpe
(common in academic eval); we also report the per-stock-pooled aggregate.

We additionally report a NAIVE baseline (always-long buy-and-hold) for
sanity context — this is approximately what an index ETF would return.

Outputs:
    results/financial_metrics_DLinear.csv  — one row per (method, horizon)
    Per-stock breakdowns are saved alongside.
"""
import os
import gc
import argparse
import json
import numpy as np
import pandas as pd
import torch

from config import SEQ_LEN, CLOSE_IDX, MODEL_SAVE_DIR, RESULTS_DIR, VALTEST_CACHE_DIR
from data_loader import UnifiedDataLoader
from models import model_dict
from train import get_config_for_model


# ─────────────────────────────────────────────────────────────────────────────
# Metric helpers
# ─────────────────────────────────────────────────────────────────────────────
def sharpe_ratio(returns, horizon_days, eps=1e-9):
    """Annualised Sharpe = mean / std * sqrt(252 / H).
    Returns NaN if std is below eps (degenerate distribution).
    """
    returns = np.asarray(returns, dtype=np.float64)
    if len(returns) < 2:
        return float("nan")
    mu = float(np.mean(returns))
    sigma = float(np.std(returns, ddof=1))
    if sigma < eps:
        return float("nan")
    return mu / sigma * np.sqrt(252.0 / horizon_days)


def max_drawdown(returns):
    """Max peak-to-trough drawdown on the equity curve formed by
    compounding the return series. Returns a fraction in [0, 1].

    Implementation note: returns are clipped to >= -0.99 to keep the
    equity curve strictly positive (a -100% return would zero out the
    account; a more-negative return is unphysical for a non-leveraged
    long-short strategy and only happens here as a numerical artefact
    from overlapping samples on stocks with extreme upward drift). We
    then compute MDD in log-space to avoid float overflow when the
    return series is very long.
    """
    returns = np.asarray(returns, dtype=np.float64)
    if len(returns) == 0:
        return float("nan")
    r = np.clip(returns, -0.99, None)
    log_eq = np.cumsum(np.log1p(r))             # cumulative log-equity
    log_peak = np.maximum.accumulate(log_eq)
    log_dd = log_peak - log_eq                  # always >= 0
    return float(1.0 - np.exp(-np.max(log_dd))) # convert back to linear drawdown


def hit_rate(pred_returns, actual_returns, eps=1e-12):
    """Fraction of samples where sign(pred) == sign(actual). Excludes
    samples where the actual change is exactly zero (rare)."""
    pred_dir = np.sign(pred_returns)
    actual_dir = np.sign(actual_returns)
    mask = np.abs(actual_returns) > eps
    if mask.sum() == 0:
        return float("nan")
    return float(np.mean(pred_dir[mask] == actual_dir[mask]))


# ─────────────────────────────────────────────────────────────────────────────
# Per-stock evaluation
# ─────────────────────────────────────────────────────────────────────────────
def evaluate_one(model_name, method, horizon, device, batch_size=512):
    print(f"\n{'='*70}\n{model_name} {method} H={horizon}\n{'='*70}")

    loader = UnifiedDataLoader(seq_len=SEQ_LEN, horizon=horizon, batch_size=batch_size)
    _, test_loader = loader.get_val_test_loaders_mmap()

    configs = get_config_for_model(model_name, horizon)
    model = model_dict[model_name](configs).to(device)
    ckpt_path = os.path.join(MODEL_SAVE_DIR, f"{model_name}_{method}_H{horizon}.pth")
    model.load_state_dict(torch.load(ckpt_path))
    model.eval()

    # Run forward pass + collect raw scaled outputs and last_close per sample
    preds_scaled, trues_scaled, last_close_scaled = [], [], []
    with torch.no_grad():
        for batch_x, batch_y in test_loader:
            bx = batch_x.float().to(device)
            out = model(bx, None)
            if isinstance(out, tuple):
                out = out[0]
            preds_scaled.append(out.cpu().numpy())
            trues_scaled.append(batch_y.numpy())
            last_close_scaled.append(bx[:, -1, CLOSE_IDX].cpu().numpy())

    preds_scaled       = np.concatenate(preds_scaled).astype(np.float64)
    trues_scaled       = np.concatenate(trues_scaled).astype(np.float64)
    last_close_scaled  = np.concatenate(last_close_scaled).astype(np.float64)

    # Inverse-scale to dollar space using each sample's stock-specific
    # close_min / close_max (already aligned with sample order since
    # test_loader uses shuffle=False).
    cmin = loader.test_close_min.astype(np.float64)
    cmax = loader.test_close_max.astype(np.float64)
    scale = cmax - cmin

    # H-day-ahead values (last step of pred / true window)
    pred_H_usd   = preds_scaled[:, -1] * scale + cmin           # [N]
    actual_H_usd = trues_scaled[:, -1] * scale + cmin           # [N]
    last_usd     = last_close_scaled  * scale + cmin            # [N]

    # H-day return from last_close to t+H
    pred_return   = (pred_H_usd   - last_usd) / np.maximum(last_usd, 1e-9)
    actual_return = (actual_H_usd - last_usd) / np.maximum(last_usd, 1e-9)

    # Long-short strategy
    position = np.sign(pred_return)
    strat_return = position * actual_return

    # Naive long-only baseline (buy & hold for H days)
    naive_return = actual_return                   # always long, no signal

    # Group by stock: each stock has a unique (close_min, close_max).
    # Use close_max as a stock identifier (collisions extremely unlikely).
    stock_id = cmax  # serves as proxy stock id
    unique_stocks = np.unique(stock_id)

    # Need to preserve TIME ORDER within each stock for the equity curve.
    # The mmap loader emits samples in (stock, ascending t) order, so
    # samples within one stock_id are already chronologically ordered.

    per_stock_rows = []
    pooled_strat_returns = []                # for pooled Sharpe (uses ALL overlapping samples)
    pooled_naive_returns = []
    pooled_strat_returns_nonoverlap = []     # for pooled MDD (non-overlapping only)
    pooled_naive_returns_nonoverlap = []

    for sid in unique_stocks:
        mask = stock_id == sid
        if mask.sum() < 30:                       # too few samples for stable stats
            continue
        # Within-stock samples are already chronologically ordered (mmap loader
        # preserves order with shuffle=False).
        s_ret = strat_return[mask]
        n_ret = naive_return[mask]
        p_ret = pred_return[mask]
        a_ret = actual_return[mask]

        # Non-overlapping subsample: take every H-th sample, representing
        # sequential, independent H-day trades. This is the only way MDD
        # is financially meaningful — overlapping samples compound the
        # same return many times, producing nonsense drawdowns.
        s_ret_nonoverlap = s_ret[::horizon]
        n_ret_nonoverlap = n_ret[::horizon]

        per_stock_rows.append({
            "stock_close_max": float(sid),
            "n_samples": int(mask.sum()),
            "n_nonoverlap_trades": int(len(s_ret_nonoverlap)),
            # Sharpe on ALL overlapping samples (statistical estimate — high N, slightly optimistic).
            "sharpe_strategy_overlap": sharpe_ratio(s_ret, horizon),
            "sharpe_naive_overlap":    sharpe_ratio(n_ret, horizon),
            # Sharpe on NON-overlapping subsample (financially realisable, but lower N).
            "sharpe_strategy": sharpe_ratio(s_ret_nonoverlap, horizon),
            "sharpe_naive":    sharpe_ratio(n_ret_nonoverlap, horizon),
            # MDD: ONLY computed on non-overlapping samples (overlapping makes MDD nonsense).
            "mdd_strategy":    max_drawdown(s_ret_nonoverlap),
            "mdd_naive":       max_drawdown(n_ret_nonoverlap),
            "hit_rate":        hit_rate(p_ret, a_ret),
            "mean_strat_return":  float(np.mean(s_ret)),
            "mean_naive_return":  float(np.mean(n_ret)),
        })
        pooled_strat_returns.append(s_ret)
        pooled_naive_returns.append(n_ret)
        pooled_strat_returns_nonoverlap.append(s_ret_nonoverlap)
        pooled_naive_returns_nonoverlap.append(n_ret_nonoverlap)

    pstock_df = pd.DataFrame(per_stock_rows)
    pooled_strat_returns           = np.concatenate(pooled_strat_returns)
    pooled_naive_returns           = np.concatenate(pooled_naive_returns)
    pooled_strat_returns_nonoverlap = np.concatenate(pooled_strat_returns_nonoverlap)
    pooled_naive_returns_nonoverlap = np.concatenate(pooled_naive_returns_nonoverlap)

    summary = {
        "Model":   model_name,
        "Method":  method,
        "Horizon": horizon,
        # ── Strategy (model-driven long-short) ────────────────────────
        # Sharpe over ALL overlapping samples (high-N statistical estimate)
        "Strategy_Sharpe_pooled_overlap":      sharpe_ratio(pooled_strat_returns, horizon),
        # Sharpe over non-overlapping samples (realistic, lower N but financially meaningful)
        "Strategy_Sharpe_pooled_nonoverlap":   sharpe_ratio(pooled_strat_returns_nonoverlap, horizon),
        "Strategy_Sharpe_mean_per_stock":      float(pstock_df["sharpe_strategy"].mean()),
        "Strategy_Sharpe_median_per_stock":    float(pstock_df["sharpe_strategy"].median()),
        "Strategy_Sharpe_std_per_stock":       float(pstock_df["sharpe_strategy"].std()),
        # MDD: ONLY non-overlapping (overlapping is mathematically meaningless)
        "Strategy_MDD_pooled":                 max_drawdown(pooled_strat_returns_nonoverlap),
        "Strategy_MDD_median_per_stock":       float(pstock_df["mdd_strategy"].median()),
        "Strategy_MDD_mean_per_stock":         float(pstock_df["mdd_strategy"].mean()),
        # Hit rate (directional accuracy of predictions)
        "HitRate_mean_per_stock":              float(pstock_df["hit_rate"].mean()),
        # ── Naive baseline (always long, buy-and-hold for H) ─────────
        "Naive_Sharpe_pooled_overlap":         sharpe_ratio(pooled_naive_returns, horizon),
        "Naive_Sharpe_pooled_nonoverlap":      sharpe_ratio(pooled_naive_returns_nonoverlap, horizon),
        "Naive_Sharpe_median_per_stock":       float(pstock_df["sharpe_naive"].median()),
        "Naive_MDD_pooled":                    max_drawdown(pooled_naive_returns_nonoverlap),
        "Naive_MDD_median_per_stock":          float(pstock_df["mdd_naive"].median()),
        # ── Sample counts ────────────────────────────────────────────
        "N_Test_Samples":   int(len(strat_return)),
        "N_Stocks_Used":    int(len(pstock_df)),
    }

    # Tag per-stock rows for the combined CSV
    pstock_df["Model"]   = model_name
    pstock_df["Method"]  = method
    pstock_df["Horizon"] = horizon

    # Cleanup before next iteration
    del model, loader, test_loader, preds_scaled, trues_scaled, last_close_scaled
    torch.cuda.empty_cache()
    gc.collect()

    return summary, pstock_df


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────
def main():
    p = argparse.ArgumentParser()
    p.add_argument("--model", default="DLinear")
    p.add_argument("--methods", nargs="+", default=["sequential", "global"])
    p.add_argument("--horizons", type=int, nargs="+", default=[5, 20, 60, 120, 240])
    args = p.parse_args()

    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    summaries, all_pstock = [], []
    for method in args.methods:
        for h in args.horizons:
            try:
                s, ps = evaluate_one(args.model, method, h, device)
                summaries.append(s)
                all_pstock.append(ps)
            except FileNotFoundError as e:
                print(f"  -> Skipping {method} H={h}: checkpoint missing ({e})")

    summary_df = pd.DataFrame(summaries)
    pstock_df  = pd.concat(all_pstock, ignore_index=True) if all_pstock else pd.DataFrame()

    out_summary = os.path.join(RESULTS_DIR, f"financial_metrics_{args.model}.csv")
    out_pstock  = os.path.join(RESULTS_DIR, f"financial_metrics_{args.model}_per_stock.csv")
    summary_df.to_csv(out_summary, index=False)
    pstock_df.to_csv(out_pstock, index=False)

    print(f"\nWrote: {out_summary}")
    print(f"Wrote: {out_pstock}")
    print("\n" + "=" * 100)
    print("AGGREGATE SUMMARY (annualised Sharpe ratios; MDD as fraction)")
    print("=" * 100)
    show_cols = [
        "Model", "Method", "Horizon",
        "Strategy_Sharpe_median_per_stock", "Naive_Sharpe_median_per_stock",
        "Strategy_MDD_median_per_stock",    "Naive_MDD_median_per_stock",
        "HitRate_mean_per_stock",
    ]
    with pd.option_context("display.float_format", "{:.4f}".format):
        print(summary_df[show_cols].to_string(index=False))


if __name__ == "__main__":
    main()
